title: "How Dev Teams Get Shit Done"
description: "Development teams use various processes to get their work done. The main few include waterfall, incremental, agile, scrumm, lean, and kanban."
baseurl: "/how-dev-teams-get-stuff-done" # the subpath of your site, e.g. /blog
url: "http://gdiminnapolis.github.io" # the base hostname & protocol for your site

contact:
  web: http://gdiminneapolis.com
  email: "minneapolis@girldevelopit.com"
  twitter: "gdimpls"
  github: "gdiminneapolis"

markdown: kramdown
collections:
  - slides

# Slide styles available include:
# - gdidefault
# - gdilight
# - gdidark
# - gdisunny
# - gdicool
# - simple
style: gdidefault

# Code syntax styles include:
# - dark
# - light
# - zenburn
syntax_style: zenburn
